
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author humam
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDonor = new javax.swing.JMenu();
        jMenuItemAddNew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemUpdateDetails = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAllDonorDetails = new javax.swing.JMenuItem();
        jMenuSearchBloodDonor = new javax.swing.JMenu();
        jMenuItemLocation = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBloodGroup = new javax.swing.JMenuItem();
        jMenuStock = new javax.swing.JMenu();
        jMenuItemIncrease = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDecrease = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDetails = new javax.swing.JMenuItem();
        jMenuDeleteDonor = new javax.swing.JMenu();
        jMenuItemDeleteDonor = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExitApplication = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuDonor.setText("Donor");

        jMenuItemAddNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAddNew.setText("Add New");
        jMenuItemAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddNewActionPerformed(evt);
            }
        });
        jMenuDonor.add(jMenuItemAddNew);
        jMenuDonor.add(jSeparator1);

        jMenuItemUpdateDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemUpdateDetails.setText("Update Details");
        jMenuItemUpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateDetailsActionPerformed(evt);
            }
        });
        jMenuDonor.add(jMenuItemUpdateDetails);
        jMenuDonor.add(jSeparator2);

        jMenuItemAllDonorDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAllDonorDetails.setText("All Donor Details");
        jMenuItemAllDonorDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAllDonorDetailsActionPerformed(evt);
            }
        });
        jMenuDonor.add(jMenuItemAllDonorDetails);

        jMenuBar1.add(jMenuDonor);

        jMenuSearchBloodDonor.setText("Search Blood Donor");

        jMenuItemLocation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemLocation.setText("Location");
        jMenuSearchBloodDonor.add(jMenuItemLocation);
        jMenuSearchBloodDonor.add(jSeparator3);

        jMenuItemBloodGroup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemBloodGroup.setText("Bood Group");
        jMenuSearchBloodDonor.add(jMenuItemBloodGroup);

        jMenuBar1.add(jMenuSearchBloodDonor);

        jMenuStock.setText("Stock");

        jMenuItemIncrease.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemIncrease.setText("Increase");
        jMenuItemIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIncreaseActionPerformed(evt);
            }
        });
        jMenuStock.add(jMenuItemIncrease);
        jMenuStock.add(jSeparator4);

        jMenuItemDecrease.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemDecrease.setText("Decrease");
        jMenuStock.add(jMenuItemDecrease);
        jMenuStock.add(jSeparator5);

        jMenuItemDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemDetails.setText("Details");
        jMenuStock.add(jMenuItemDetails);

        jMenuBar1.add(jMenuStock);

        jMenuDeleteDonor.setText("Delete Donor");

        jMenuItemDeleteDonor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemDeleteDonor.setText("Delete Donor");
        jMenuItemDeleteDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteDonorActionPerformed(evt);
            }
        });
        jMenuDeleteDonor.add(jMenuItemDeleteDonor);

        jMenuBar1.add(jMenuDeleteDonor);

        jMenuExit.setText("Exit");

        jMenuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItemLogout);
        jMenuExit.add(jSeparator6);

        jMenuItemExitApplication.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemExitApplication.setText("Exit Application");
        jMenuItemExitApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitApplicationActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItemExitApplication);

        jMenuBar1.add(jMenuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAllDonorDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAllDonorDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAllDonorDetailsActionPerformed

    private void jMenuItemIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIncreaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemIncreaseActionPerformed

    private void jMenuItemDeleteDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteDonorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDeleteDonorActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout", "Select", JOptionPane.YES_NO_OPTION);
        
        if(a == 0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemExitApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitApplicationActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Close Application", "Select", JOptionPane.YES_NO_OPTION);
        
        if(a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemExitApplicationActionPerformed

    private void jMenuItemAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddNewActionPerformed
        // TODO add your handling code here:
        new AddNewDonor().setVisible(true);
    }//GEN-LAST:event_jMenuItemAddNewActionPerformed

    private void jMenuItemUpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateDetailsActionPerformed
        // TODO add your handling code here:
        new UpdateDonor().setVisible(true);
    }//GEN-LAST:event_jMenuItemUpdateDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDeleteDonor;
    private javax.swing.JMenu jMenuDonor;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItemAddNew;
    private javax.swing.JMenuItem jMenuItemAllDonorDetails;
    private javax.swing.JMenuItem jMenuItemBloodGroup;
    private javax.swing.JMenuItem jMenuItemDecrease;
    private javax.swing.JMenuItem jMenuItemDeleteDonor;
    private javax.swing.JMenuItem jMenuItemDetails;
    private javax.swing.JMenuItem jMenuItemExitApplication;
    private javax.swing.JMenuItem jMenuItemIncrease;
    private javax.swing.JMenuItem jMenuItemLocation;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemUpdateDetails;
    private javax.swing.JMenu jMenuSearchBloodDonor;
    private javax.swing.JMenu jMenuStock;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
